### PR TITLE
Fix dangerous Default impl for Point

### LINKED ISSUE #150: Point default is Zero while marked as NonZero

### PR DESCRIPTION
**Pull request by LLFourn**
You could get a zero point in a NonZero Point

fixes #150

### CODE REVIEW

**Review by nickfarrow — APPROVED** [review]

File: secp256kfun/src/point.rs [hunk 1]
```diff
@@ -159,12 +172,35 @@ impl<T: PointType, S> Point<T, S, NonZero> {
...
+    where
+        T: PointType,
+    {
         let normalized = self.normalize();
         let needs_negation = !normalized.is_y_even();
         let negated = normalized.conditional_negate(needs_negation);
         (Point::from_inner(negated.0, EvenY), needs_negation)
     }
+
+    /// Returns the generator point [`G`] defined in [_Standards for Efficient Cryptography_].
```
Comment (nickfarrow) [inline secp256kfun/src/point.rs:185]: Docs don't like this [`G`]
